name: Static Analysis

on:
  workflow_call:
    secrets:
      QODANA_TOKEN:
        required: false
        description: Qodana token

permissions:
  security-events: write
  contents: write
  checks: write
  pull-requests: write

jobs:
  Qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # TODO: Java setup?
      - name: Qodana Scan
        uses: JetBrains/qodana-action@v2023.3
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
      - name: Upload to GitHub code scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
